### ISSUE TITLE
[feat] 페이지의 기본 레이아웃 추가

### ISSUE THREAD

**Issue by osw6858** [hoops-project/frontend#1]
![image](https://github.com/hoops-project/frontend/assets/107461545/8c9e05bd-7eab-4341-9ddd-0ef51bcc7a9d)
- 가장 기본이 되는 페이지 레이아웃을 잡을 예정입니다.
- 헤더와 푸터는 따로 컴포넌트로 분리 예정입니다.
- 페이지에 따라 배경색이 다른 경우를 대비하여 만들 예정입니다.
- 헤더의 검색창은 컴포넌트로 분리 하겠습니다.

**Comment by KimYeoungChan** [comment]
네 확인했습니다.
